version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - /app/node_modules

  database:
    image: postgres
    restart: always
    ports:
      - '54320:5432'
    environment:
      DATABASE_HOST: localhost
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: exam
